---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubepet.grapefruitcat030.github.io
  resources:
  - virtualpets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubepet.grapefruitcat030.github.io
  resources:
  - virtualpets/finalizers
  verbs:
  - update
- apiGroups:
  - kubepet.grapefruitcat030.github.io
  resources:
  - virtualpets/status
  verbs:
  - get
  - patch
  - update
